#image: justinmoon/mooniversity:0.0.1
image:
    file: Dockerfile
tasks:
    - command: >
        pip3 install -r requirements.txt &&
        bitcoind -testnet -prune=550 > bitcoin.log 2>&1 & &&
        clear
