#image: justinmoon/mooniversity:0.0.1
image:
    file: Dockerfile
tasks:
    - command: "pip3 install -r requirements.txt"
    - command: "nohup ./bitcoin.sh > ~/.bitcoin.log 2>&1 &"
    - command: "clear"

