#image: justinmoon/mooniversity:0.0.1
image:
    file: Dockerfile
tasks:
    - command: "cat bashrc >> ~/.bashrc"
    - command: "source ~/.bashrc"
    - command: "nohup pip3 install -r requirements.txt > /dev/null 2>&1 &"
    - command: "nohup ./bitcoin.sh > ~/.bitcoin.log 2>&1 &"
    - command: "clear"

